# Generated by Django 4.1.3 on 2022-11-19 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique favorite recipe for user',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientamount',
            name='unique ingredients recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique cart user',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не введено колличество ингредиентов')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не введено время')], verbose_name='Время приготовления'),
        ),
    ]
